on:
  http:
    url: https://v2.jokeapi.dev/joke/Any?type=single
    method: GET
    config:
      force: true
    cron: "*/10 * * * *"

jobs:
  send_joke:
    name: Send joke to webhook
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request to webhook
        uses: actionsflow/axios@v1
        with:
          url: 'https://hooks.slack.com/services/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'
          method: POST
          body: '{"text": "${{ on.http.outputs.data }}"}'
