on:
  rss:
    url: https://v2.jokeapi.dev/joke/Any?type=single&amount=1&format=xml
    config:
      outputsMode: single
    cron: "*/10 * * * *"

jobs:
  request:
    name: Send joke to webhook
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request to webhook
        uses: actionsflow/axios@v1
        with:
          url: 'https://hooks.slack.com/services/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'
          method: POST
          body: '{"text": "${{ on.rss.outputs.item.description }}"}'
