on:
  rss:
    url: https://hnrss.org/newest?points=700&count=22
jobs:
  write_to_file:
    name: Write to File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Write Outputs to File
        env:
          title: ${{on.rss.outputs.title}}
          contentSnippet: ${{on.rss.outputs.contentSnippet}}
          link: ${{on.rss.outputs.link}}
        run: |
          echo "Title: $title" >> rss-results.txt
          echo "Content Snippet: $contentSnippet" >> rss-results.txt
          echo "Link: $link" >> rss-results.txt

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add rss-results.txt
          git commit -m "Update output.txt with new RSS data"
          git push





#on:
#  rss:
#    url: https://hnrss.org/newest?points=300&count=3
#jobs:
#  print:
#    name: Print
#    runs-on: ubuntu-latest
#    steps:
#      - name: Print Outputs
#        env:
#          title: ${{on.rss.outputs.title}}
#          contentSnippet: ${{on.rss.outputs.contentSnippet}}
#          link: ${{on.rss.outputs.link}}
#        run: |
#          echo title: $title
#          echo contentSnippet: $contentSnippet
#          echo link: $link
